---
abstract: 'A SPARQL Protocol Endpoint implementation'
author:
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: zlib
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Endpoint
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Carp: 0
  Config::JFDI: 0
  Data::Dumper: 0
  File::ShareDir: 0
  HTML::HTML5::Parser: 0
  HTML::HTML5::Writer: 0
  HTTP::Negotiate: 0
  Hash::Merge::Simple: 0
  IO::Compress::Gzip: 0
  Plack::Request: 0
  Plack::Response: 0
  RDF::Query: 2.905
  RDF::RDFa::Generator: 0.102
  RDF::Trine: 0.134
  XML::LibXML: 1.7
  perl: 5.8.0
resources:
  homepage: http://search.cpan.org/dist/RDF-Endpoint/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kasei/perlrdf/
version: 0.03_01
